### ISSUE TITLE
Getting null pointer exception when toEnvironmentBlock flow has null paramater

### ISSUE THREAD

**Issue by pradeep-nagarajan** [webcompere/system-stubs#56]
Getting null pointer exception when toEnvironmentBlock flow has null paramater in "invocationOnMock" variable in EnvironmentVariableMocker static block

Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "m" is null
    at uk.org.webcompere.systemstubs.environment.EnvironmentVariableMocker.toEnvironmentBlockWindows(EnvironmentVariableMocker.java:83)
    at uk.org.webcompere.systemstubs.environment.EnvironmentVariableMocker.simulateToEnvironmentBlock(EnvironmentVariableMocker.java:69)
    at uk.org.webcompere.systemstubs.environment.EnvironmentVariableMocker.lambda$static$0(EnvironmentVariableMocker.java:35)
    at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:111)
    at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
    at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
    at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
    at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handleStatic(MockMethodAdvice.java:148)

**Comment by ashleyfrieze** [comment]
@pradeep-nagarajan  - can I see the test code you've written and how you're using the EnvironmentVariables stub.

**Comment by pradeep-nagarajan** [comment]
@ashleyfrieze I am using Spring Boot 3 Junit 5 test cases (Jupiter), with @SystemStub annotation using 2.0.2 version, Java 17

**Comment by pradeep-nagarajan** [comment]
Code snippet

```
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.test.context.SpringBootTest;
import uk.org.webcompere.systemstubs.environment.EnvironmentVariables;
import uk.org.webcompere.systemstubs.jupiter.SystemStub;
import uk.org.webcompere.systemstubs.jupiter.SystemStubsExtension;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ExtendWith(SystemStubsExtension.class)
public class StubTest {

    @SystemStub
    protected static EnvironmentVariables environmentVariables;

    @Test
    public void test() {
        Assertions.assertNotNull(environmentVariables);
    }

}
```

**Comment by ashleyfrieze** [comment]
@pradeep-nagarajan - that's interesting. And this test is failing? That's odd, because the function that's being called "toEnvironmentBlock" is usually called when something tries to start a process. Does your SpringBoot application invoke any processes?

**Comment by pradeep-nagarajan** [comment]
@ashleyfrieze We are simulating an integration testing via Junit, like using embedded DB (H2).  So, we will bring up the spring boot server (embedded tomcat) to test our APIs. Just FYI, the same setup is working up to 1.2.0 version, where you don't have this change. This NPE is introduced from 2.0.0 version, refer the below file history.

https://github.com/webcompere/system-stubs/commits/main/system-stubs-core/src/main/java/uk/org/webcompere/systemstubs/environment/EnvironmentVariableMocker.java

**Comment by ashleyfrieze** [comment]
@pradeep-nagarajan - yes, the `EnvironmentMocker` is needed for the v2 release train, which you'd need if you were on Java 16 or greater. If you're not on the later Java, then downgrade. I'll fix the NPE.

It would be useful to see what's invoking this though. Can you share more of the call stack?

And have you any other special settings that might be causing multiple processes to be invoked from your test thread?

**Comment by pradeep-nagarajan** [comment]
@ashleyfrieze Please find the full trace, yes we are using embedded mongo DB which starts a process with Spring Boot

Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "m" is null
    at uk.org.webcompere.systemstubs.environment.EnvironmentVariableMocker.toEnvironmentBlockWindows(EnvironmentVariableMocker.java:83)
    at uk.org.webcompere.systemstubs.environment.EnvironmentVariableMocker.simulateToEnvironmentBlock(EnvironmentVariableMocker.java:69)
    at uk.org.webcompere.systemstubs.environment.EnvironmentVariableMocker.lambda$static$0(EnvironmentVariableMocker.java:35)
    at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:111)
    at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
    at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
    at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
    at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handleStatic(MockMethodAdvice.java:148)
    at java.base/java.lang.ProcessEnvironment.toEnvironmentBlock(ProcessEnvironment.java:348)
    at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:105)
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
    at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:177)
    at de.flapdoodle.embed.process.types.RunningProcess.start(RunningProcess.java:76)
    at de.flapdoodle.embed.mongo.transitions.MongoServerStarter.result(MongoServerStarter.java:119)
    at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:58)
    at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:46)
    at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:176)

**Comment by ashleyfrieze** [comment]
@pradeep-nagarajan - v 2.0.3 will fix this. We're just waiting for maven central to run through its deployment/replication.

**Comment by ashleyfrieze** [comment]
It's deployed from nexus, just waiting for propagation.

**Comment by ashleyfrieze** [comment]
@pradeep-nagarajan - you're good to go. It's showing up on maven central now.
